title: INTRO2AI — Ghi chú ôn tập
description: Hệ thống hóa kiến thức môn Nhập môn Trí tuệ Nhân tạo (Introduction to AI)
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
show_downloads: false
